# Generated by Django 6.0 on 2026-01-02 17:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur')),
                ('transaction_type', models.CharField(choices=[('expense', 'Dépense'), ('income', 'Revenu')], default='expense', max_length=10, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='budget.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200, unique=True, verbose_name='Motif')),
                ('confidence', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confiance')),
                ('is_user_validated', models.BooleanField(default=False, verbose_name="Validée par l'utilisateur")),
                ('usage_count', models.IntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='budget.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Règle de catégorisation',
                'verbose_name_plural': 'Règles de catégorisation',
                'ordering': ['-confidence', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('label', models.TextField(verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validée')),
                ('import_hash', models.CharField(max_length=32, unique=True, verbose_name="Hash d'import")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='budget_tran_date_dd1bca_idx'), models.Index(fields=['category'], name='budget_tran_categor_d9e551_idx')],
            },
        ),
    ]
