# Generated by Django 6.0 on 2026-06-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-period'], 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        # Supprimer l'ancienne contrainte avant de toucher aux colonnes qu'elle référence
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.DateField(default='2026-01-01', verbose_name='Mois (1er du mois)'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('category', 'period')},
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Plafond mensuel'),
        ),
    ]
