# Generated by Django 6.0 on 2026-07-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_replace_dates_with_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorizationrule',
            name='rejected_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de rejets'),
        ),
    ]
