# Generated by Django 6.0 on 2026-07-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_categorizationrule_rejected_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='applied_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_transactions', to='budget.categorizationrule', verbose_name='Règle appliquée'),
        ),
    ]
